version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /opt/coinpl:/coinpl
    links:
      - db:mysql
    container_name: coinpl_web_1
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    container_name: coinpl_db_1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: coinpl

