version: '2'
services:
  server:
    restart: always
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./coinpl/static:/coinpl/coinpl/static
    links:
      - web:web
      - swagger:swagger
    ports:
      - "80:80"
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /opt/coinpl:/coinpl
    links:
      - db:mysql
    container_name: coinpl_web_1
    depends_on:
      - db
      - mongo
    restart: always
  db:
    image: mysql:5.7
    restart: always
    container_name: coinpl_db_1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: coinpl
      MYSQL_USER: coinpl_adm
      MYSQL_PASSWORD: coinpl_adm
  mongo:
    image: mongo:3.0.15
    restart: always
    container_name: coinpl_mongo_1
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
    - "API_URL=https://raw.githubusercontent.com/exleym/coinpl/master/coinpl/static/openapi.yml"
    container_name: coinpl_swagger_1
    restart: always
