"""initial commit

Revision ID: 46897a040139
Revises: 
Create Date: 2017-07-29 12:46:15.920553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46897a040139'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('coin_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pl_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('build_notes', sa.Text(), nullable=True),
    sa.Column('pr_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('effective', sa.DateTime(), nullable=True),
    sa.Column('cut_time', sa.DateTime(), nullable=True),
    sa.Column('pl_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pl_version_id'], ['pl_versions.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('trade_time', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('execution_price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.Column('cut_id', sa.Integer(), nullable=True),
    sa.Column('cut_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ),
    sa.ForeignKeyConstraint(['cut_id'], ['cuts.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('cut_id', sa.Integer(), nullable=True),
    sa.Column('effective', sa.Date(), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('invested_value', sa.Float(), nullable=True),
    sa.Column('superceded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cut_id'], ['cuts.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_data')
    op.drop_table('holdings')
    op.drop_table('transactions')
    op.drop_table('cuts')
    op.drop_table('wallets')
    op.drop_table('pl_versions')
    op.drop_table('exchanges')
    op.drop_table('coins')
    # ### end Alembic commands ###
